version: '3.8'

services:
  api:
    build: .
    image: raisa-jose/trademarkia-ai-search:latest
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    # This allows to see logs in real-time
    stdin_open: true
    tty: true